export const ROUTES = {
  HOME: '/',
  SEARCH: '/search',
  LOGIN: '/login',
  REGISTER: '/register',
  BOOK: '/book',
  BOOKING_SUCCESS: '/booking/success',
  VENUE: (slug: string) => `/venues/${slug}` as const,
  PROFILE: '/profile',
  PROFILE_FAVORITES: '/profile/favorites',
  PROFILE_BOOKINGS: '/bookings',
  PROFILE_SETTINGS: '/settings',
  BUSINESS: '/business',
  BUSINESS_VENUES: '/business/venues',
  BUSINESS_ADD_VENUE: '/business/venues/add',
  BUSINESS_EDIT_VENUE: (id: string) => `/business/venues/${id}/edit` as const,
  BUSINESS_BOOKINGS: '/business/bookings',
  BUSINESS_CALENDAR: '/business/calendar',
  BUSINESS_REVIEWS: '/business/reviews',
  BUSINESS_REVENUE: '/business/revenue',
  BUSINESS_SETTINGS: '/business/settings',
  ADMIN: '/admin',
  ADMIN_USERS: '/admin/users',
  ADMIN_VENUES: '/admin/venues',
  ADMIN_VENUES_REVIEW: '/admin/venues/review',
  ADMIN_BOOKINGS: '/admin/bookings',
  ADMIN_REVENUE: '/admin/revenue',
  ADMIN_SETTINGS: '/admin/settings',
  PRIVACY: '/privacy',
  TERMS: '/terms',
} as const
